
# Site settings

url: "https://cchanningallen.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

# Currently unused, commenting these for now
# baseurl: /personal-jekyll-theme

# google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

#############
# HTML Head #
#############

author: "Channing Allen"
lang: "en"
title: "Channing Allen"
favicon: "/img/favicon-angle-double-left.ico"
description: "Blog and website of Channing Allen."
keywords: "channing, allen, website, blog"

################
# Intro layout #
################

# TODO: add favicon
black-favicon: ""
background-img: "../img/japan-mountains.jpg"
me-img: "/img/burn-portrait-1.jpg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: False	# Shuffle the lines.
loop: False
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Life starts at the end of your comfort zone."

########
# Blog #
########

post-preview-words: 128

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "panossakkos"

###############
# Life Events #
###############

events:
  - image: ""
    date: "April 2015 - Today"
    description: "Full-Stack Web App Developer<br><small>(freelance)</small>"
  - image: ""
    date: "October 2014 - March 2015"
    description: "Engineering Lead, Usability Team<br><small>(CrowdFlower)</small>"
  - image: ""
    date: "March 2014 - October 2014"
    description: "Software Engineer<br><small>(CrowdFlower)</small>"
  - image: ""
    date: "August 2013 - February 2014"
    description: "Enterprise Software Engineer<br><small>(CrowdFlower)</small>"
  - image: ""
    date: "March 2013 - July 2013"
    description: "Technical Analyst<br><small>(CrowdFlower)</small>"
  - image: ""
    date: "December 2012 - February 2013"
    description: "Alchemist<br><small>(CrowdFlower)</small>"
  - image: ""
    date: "July 2012 - October 2012"
    description: "Finance Product Specialist<br><small>(Sageworks)</small>"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "cchanningallen@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/cchanningallen"
  - title: "github"
    url: "https://github.com/cchanningallen"
  - title: "facebook"
    url: "https://facebook.com/cchanningallen"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  # Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
