# Site settings

url: "https://cchanningallen.github.io"

# Currently unused, commenting these for now
#baseurl: /
# google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

#############
# HTML Head #
#############

author: "Channing Allen"
lang: "en"
title: "Channing Allen"
favicon: "/img/favicon-angle-double-left.ico"
description: "Personal site of Channing Allen."
keywords: "channing, allen, website, blog"

################
# Intro layout #
################

# TODO: add favicon
black-favicon: ""
background-img: "../img/japan-mountains.jpg"
me-img: "/img/burn-portrait-1.jpg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: False	# Shuffle the lines.
loop: False
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Life starts at the end of your comfort zone."

###############
# Life Events #
###############

events:
  - image: "/img/career/homebase.png"
    date: "Feb 2017 - Today"
    description: "Senior Software Engineer<br><small>Homebase</small>"
  - image: ""
    date: "Apr 2016 - Jan 2017"
    description: "Consultant, Front-End Architecture"
  - image: "/img/career/gradle.png"
    date: "Nov 2015 - Jun 2016"
    description: "Lead of Front-End Engineering<br><small>(Gradle)</small>"
  - image: "/img/career/crowdflower.png"
    date: "Oct 2014 - Mar 2015"
    description: "Engineering Lead, Usability Team<br><small>(CrowdFlower)</small>"
  - image: "/img/career/crowdflower.png"
    date: "Dec 2012 - Oct 2014"
    description: "Software Engineer<br><small>(CrowdFlower)</small>"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "cchanningallen@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/cchanningallen"
  - title: "github"
    url: "https://github.com/cchanningallen"
  - title: "facebook"
    url: "https://facebook.com/cchanningallen"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Navigation bar links

pages_list:
  About: 'about'
  Career: 'career'
  Contact: 'contact'

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"  ]
